# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  pull_request:
    types:
      - labeled

jobs:
  generate-checksum:
    if: github.event.label.name == 'depfu'
    runs-on: ubuntu-latest

    steps:
      - name: install dependencies
        run: sudo gem install bundler
      - uses: actions/checkout@v2
      - name: Generate the checksum
        run: |
          git config --global user.name "Victor Pereira"
          git config --global user.email "vpereira@suse.com"
          bash generate_checksum.sh
